### PR TITLE
feat(global) add developer intern

### PR DESCRIPTION
**Pull request by BruceRW3**
Added Bruce Wiggleston as Developer Intern
Created mark down file for Bruce.
Also corrected order place in markdown file.

### CODE REVIEW

**Review by jordanpowell88 — CHANGES_REQUESTED** [review]
Let's limit this PR scope to just adding your markdown file

**Comment by BruceRW3** [comment]
Added global e2e test for markdown pages for changing language

Closes #9

**Comment by BruceRW3** [comment]
Corrected Hannah Swartz spelling error on md file.
Removed requested files from .gitignore.

**Comment by jordanpowell88** [comment]
This PR is a duplicate of #78

**Pull request closed without merging**
